# Programação para advogados

Graduação em direito FGV Direito Rio

#### - [Dicionários](#aula4)

#### - [Resumo](#resumo)

#### - [Exercícios](#exercicio)

<a id=aula4></a>
# Aula 4 - Dicionários

Se podemos fazer muito com listas e tuplas, podemos fazer muito mais com dicionários! Nesta aula, veremos como podemos associar clientes de um escritório aos processos atrelados a eles.

Raramente queremos fazer uma simples lista de clientes. Para isso, podemos usar outras tecnologias. Se vamos *programar*, provavelmente queremos fazer algo mais sofisticado. No mínimo, queremos associar cada um dos nossos clientes aos processos atrelados a eles.

Vamos relembrar nossa lista de clientes do escritório hipotético da última aula:

In [1]:
lista_clientes = [
    "Maria Berenice Dias",
    "Pontes de Miranda",
    "José Afonso da Silva",
    "Aliomar Baleeiro",
    "Guilherme Nucci",
    "Nelson Hungria",
    "Sobral Pinto",
    "Evandro Lins e Silva",
]
len(lista_clientes)

8

De acordo com a lista acima, temos oito clientes. Mas pode ser que tenhamos 20 processos em trâmite (os números de processo foram gerados aleatoriamente e não correspondem ao formato de nenhum tribunal que conhecemos):

In [2]:
lista_processos = [
    "2002.766393",
    "2011.487453",
    "2004.314066",
    "1998.516307",
    "2011.491429",
    "2003.714034",
    "2000.695102",
    "2012.628045",
    "2017.462447",
    "1996.518281",
    "1997.416985",
    "2002.321557",
    "2002.737116",
    "2011.655314",
    "1990.414436",
    "2012.369756",
    "1996.773047",
    "1995.344760",
    "1993.328622",
    "2016.681535",
]

Imagine um estagiário confuso olhando para essas duas listas. Não seria muito mais útil se pudéssemos guardar essas informações de maneira combinada? De maneira que cada cliente esteja relacionado aos seus processos? Claro que sim! E para isso, o Python tem uma estrutura chamada **dicionário** ou `dict`.

<br>
<br>
    <img src=https://i.imgur.com/OcSofVI.jpg style = "width:50%">
    <center> <i> Imagem meramente ilustrativa </i> </center>
    <!-- fonte open source: https://images.unsplash.com/photo-1524639064490-254e0a1db723?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80 -->
    
<i> A imagem acima contém a ilustração de um dicionário físico.</i>

Assim como um dicionário físico associa certas palavras a certas definições, um `dict` associa certas *chaves*, ou `keys`, a certos *valores* ou `values`. A sintaxe de criação de um dicionário é um pouco diferente daquela que usamos para gerar listas. Enquanto no caso de listas usamos colchetes (`[]`) para deifnir os limites, no caso do dicionário usamos chaves (`{}`). Da mesma forma, como agora temos pares, devemos sempre declarar cada item do nosso dicionário com a sintaxe `chave : valor`. Podemos ver como isso funciona criando um dicionário chamado `dicionario_clientes` e começando a alimentá-lo.

In [3]:
dicionario_clientes = {
    "Maria Berenice Dias": "1990.414436",
    "Sobral Pinto": "1993.328622",
}

Com a sintaxe acima, podemos associar o "cliente" Maria Berenice Dias com o processo 1990.414436 e o "cliente" Sobral Pinto com o processo 1993.328622. Criamos nosso primeiro `dict`:

In [4]:
type(dicionario_clientes)

dict

Agora, se quisermos consultar nosso dicionário para saber quais processos estão atrelados a Maria Berenice Dias, por exemplo, basta chamarmos a chave 'Maria Berenice Dias' entre colchetes (`[]`) após o nome do dicionário. É parecido com o que faríamos com o índice de uma lista:

In [5]:
dicionario_clientes["Maria Berenice Dias"]

'1990.414436'

Dicionários são pares de *chaves* e *valores*, de maneira que os métodos `.keys()` e `.values()` são dois dos mais importantes relacionados a essa estrutura de dados.

O método `.keys()` serve para sabermos quais são as *chaves* do nosso dicionário. No contexto de `dicionario_clientes`, isso significa olhar quem são nossos clientes:

In [6]:
dicionario_clientes.keys()

dict_keys(['Maria Berenice Dias', 'Sobral Pinto'])

`.values()`, por sua vez, retorna os números de processo:

In [7]:
dicionario_clientes.values()

dict_values(['1990.414436', '1993.328622'])

Lembre-se que temos mais processos do que clientes, de maneira que alguns clientes vão ter múltiplos processos. Um valor de um dicionário pode ser uma lista! Vamos adicionar três processos diferentes ao cliente Guilherme Nucci. Repare que adicionar itens a um dicionário é diferente do que ocorre com uma lista. Não precisamos chamar um método próprio, já que podemos simplesmente declarar uma chave inédita:

In [8]:
dicionario_clientes["Guilherme Nucci"] = ['2003.714034', '2000.695102', '2012.628045']
print(dicionario_clientes)

{'Maria Berenice Dias': '1990.414436', 'Sobral Pinto': '1993.328622', 'Guilherme Nucci': ['2003.714034', '2000.695102', '2012.628045']}


<a id=exercicio></a>
# Exercício

Temos agora um dicionário contendo três dos nossos oito clientes e cinco dos nossos 20 processos. Termine de fazer essa transposição! Lembre-se que cada um dos clientes deve ser uma chave e que cada processo só pode aparecer uma única vez nos valores do nosso dicionário.

In [9]:
#escreva seu código aqui


In [ ]:
from correcoes import aula4_ex1
aula4_ex1(dicionario_clientes)

Dicionários, na verdade, são ainda mais potentes do que podemos imaginar a partir do exemplo acima. Afinal, cada processo contém uma série de informações próprias que também gostaríamos de saber, coisas como qual é o órgão julgador daquele processo, qual foi a data de protocolo do processo, em que fase processual ele se encontra, e assim por diante.

Assim como podemos ter listas de listas, também podemos ter dicionários como valores de dicionários. Assim, um dicionário hipotético mais complexo poderia ter a seguinte estrutura:

In [10]:
dicionario_completo = {}
dicionario_completo["Guilherme Nucci"] = {
    "2003.714034": {
        "Órgão julgador": "80ª Vara Cível",
        "data_protocolo": "2003-08-19",
        "fase_atual": "aguardando sentença",
    },
    "2000.695102": {
        "Órgão julgador": "STF",
        "data_protocolo": "2000-05-21",
        "fase_atual": "Recurso Extraordinário",
    },
    "2012.628045": {
        "Órgão julgador": "81ª Vara Cível",
        "data_protocolo": "2012-10-01",
        "fase_atual": "Embargos de Declaração",
    },
}

Nessa estrutura mais complexa, podemos primeiro verificar quais processos estão atrelados ao autor Guilherme Nucci:

In [11]:
dicionario_completo["Guilherme Nucci"]

{'2003.714034': {'Órgão julgador': '80ª Vara Cível',
  'data_protocolo': '2003-08-19',
  'fase_atual': 'aguardando sentença'},
 '2000.695102': {'Órgão julgador': 'STF',
  'data_protocolo': '2000-05-21',
  'fase_atual': 'Recurso Extraordinário'},
 '2012.628045': {'Órgão julgador': '81ª Vara Cível',
  'data_protocolo': '2012-10-01',
  'fase_atual': 'Embargos de Declaração'}}

Para depois perguntar especificamente pelo processo 2000.695102, por exemplo:

In [12]:
dicionario_completo["Guilherme Nucci"]["2000.695102"]

{'Órgão julgador': 'STF',
 'data_protocolo': '2000-05-21',
 'fase_atual': 'Recurso Extraordinário'}

E assim por diante. Repare que estamos passando as chaves uma após a outra: primeiro, selecionamos o valor atrelado à chave "Guilherme Nucci" no `dicionario_completo` para depois buscar a chave "2000.695102" nesse novo dicionário que retornou da primeira busca.

Essa estrutura recursiva (ou "nested", para usar o termo técnico) pode se tornar bastante complexa. Mais adiante, aprenderemos a usar estruturas mais abstratas de dados que ajudam a reduzir essa complexidade.

Por enquanto, queremos apenas transmitir o poder potencial dos dicionários e sua capacidade de representar estruturas complexas de dados, contendo vários níveis diferentes, com informações cada vez mais locais a respeito das informações que buscamos.

Repare que não podemos usar o mesmo tipo de referência de índices que usamos no caso de listas. Se pedirmos o primeiro item de `dicionario_completo`, o Python não sabe o que fazer:

In [13]:
dicionario_completo[1]

KeyError: 1

<i>A execução da célula acima resulta em um erro do tipo KeyError (Erro de chave). A mensagem de erro é:

    KeyError: 1
</i>

Isso acontece porque não temos nenhuma chave (`key`) identificada pelo `int` 1. Dicionários só aceitam referências a suas chaves. O mesmo vale para remover itens. Se lembrarmos do método `.pop()` quando aplicado a listas, perceberemos que, naquele caso, `.pop()` recebe um `int` representando o índice para realizar a remoção do item. No caso dos dicionários, `.pop()` recebe uma chave. Como exemplo, vamos supor que o processo 2000.695102, relativo ao dicionário acima, termine e precise ser retirado. Podemos usar o método `.pop()`:

In [14]:
dicionario_completo["Guilherme Nucci"].pop("2000.695102")

{'Órgão julgador': 'STF',
 'data_protocolo': '2000-05-21',
 'fase_atual': 'Recurso Extraordinário'}

Retiramos do dicionário atrelado ao autor Guilherme Nucci (que acessamos através de `dicionario_completo["Guilherme Nucci"]`) o processo número 2000.695102. Quando imprimimos novamente o dicionário, vemos apenas os outros dois processos que incluímos inicialmente.

In [15]:
dicionario_completo

{'Guilherme Nucci': {'2003.714034': {'Órgão julgador': '80ª Vara Cível',
   'data_protocolo': '2003-08-19',
   'fase_atual': 'aguardando sentença'},
  '2012.628045': {'Órgão julgador': '81ª Vara Cível',
   'data_protocolo': '2012-10-01',
   'fase_atual': 'Embargos de Declaração'}}}

Assim como fizemos com listas, também podemos checar se a exclusão foi feita usando a sintaxe `in`:

In [16]:
'2000.695102' in dicionario_completo["Guilherme Nucci"]

False

Agora imagine que o processo 2012.628045 teve os embargos de declaração negados e um recurso de apelação interposto. Como podemos alterar somente esse campo do dicionário? Usando o método `.update()`:

In [17]:
dicionario_completo["Guilherme Nucci"]["2012.628045"].update({'fase_atual': 'Recurso de apelação'})

In [18]:
dicionario_completo

{'Guilherme Nucci': {'2003.714034': {'Órgão julgador': '80ª Vara Cível',
   'data_protocolo': '2003-08-19',
   'fase_atual': 'aguardando sentença'},
  '2012.628045': {'Órgão julgador': '81ª Vara Cível',
   'data_protocolo': '2012-10-01',
   'fase_atual': 'Recurso de apelação'}}}

O método `.update()` toma como argumento um dicionário e altera no primeiro dicionário (variável anterior ao ponto) apenas os pares de chaves e valores mencionados nele. Assim, Órgão julgador e data_protocolo se mantêm inalterados. Apenas a `fase_atual` é atualizada para constar que agora não estamos mais na fase de embargos de declaração, mas sim na de recurso de apelação.

Dado que estamos na fase de apelação, porém, imaginando que o recurso foi recebido pelo juízo *a quo*, precisamos atualizar também o órgão julgador! Use o método `.update()` na célula abaixo para registrar que o processo foi distribuído para a "60ª Câmara Cível". Após, rode o código de correção na célula seguinte.

In [19]:
#escreva seu código aqui


In [ ]:
from correcoes import aula4_ex2
aula4_ex2(dicionario_completo)

#### Construtor `dict`

Podemos construir dicionários usando uma sintaxe alternativa. Algumas células acima, criamos um dicionário com a linha `dicionario_completo = {}` e adicionamos itens subsequentemente ao dicionário com a sintaxe `dicionario["chave"] = valor`. Uma alternativa é usar o construtor de dicionários. Vamos recriar o processo 2003.714034 usando essa nova sintaxe:

In [20]:
dict_processo = dict(
    num_processo="2003.714034",
    orgao_julgador="80ª Vara Cível",
    data_protocolo="2003-08-19",
    fase_atual="aguardando sentença",
)
dict_processo

{'num_processo': '2003.714034',
 'orgao_julgador': '80ª Vara Cível',
 'data_protocolo': '2003-08-19',
 'fase_atual': 'aguardando sentença'}

<a id=resumo></a>
# Resumo

Nesta aula, vimos como funcionam os dicionários em Python:

* Dicionários são uma estrutura de dados que permite unir certas chaves (`keys`) a certos valores (`values`), assim como ocorre com dicionários físicos.
* Podemos guardar listas ou até mesmo dicionários como valores de um dicionário, o que significa que dicionários podem ser "nested", no linguajar técnico.
* Podemos adicionar novos pares de chaves e valores a um dicionário usando a sintaxe `dicionario[chave] = valor`.
* Além disso, temos métodos predefinidos para remover itens (`.pop()`) e atualizar (`.update()`) valores guardados em um dicionário.
* Enquanto acessamos os itens de uma lista a partir de seus índices, acessamos os itens de um dicionário através de suas chaves e apenas através delas.
* Finalmente, vimos outros modos de criar dicionários.

# Exercício extra

Imagine que você acabou de terminar a faculdade, foi aprovado na OAB e está pronto para começar o seu escritório. Você fecha contratos com algumas pessoas físicas que concordaram em pagar um valor mensal em troca dos seus serviços de consultoria jurídica. Você precisa guardar certas informações a respeito de seus clientes e decide criar um dicionário com a "idade", o "cpf" e o "valor_mensal" devido por cada um. Faça isso (inventando os valores) para seus clientes (é necessário que você tenha pelo menos um cliente) e salve o resultado em uma variável chamada `dict_clientes` (esta variável também deve ser um dicionário).

In [ ]:
#seu código aqui!


In [ ]:
from correcoes import exercicio_extra3
exercicio_extra3(dict_clientes)